language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="routes:."
  - DISTRO="ubuntu"
  matrix:
  - PACKAGE="routes" OCAML_VERSION="4.04"
  - PACKAGE="routes" OCAML_VERSION="4.05"
  - PACKAGE="routes" OCAML_VERSION="4.06"
  - PACKAGE="routes" OCAML_VERSION="4.07"
